### ISSUE TITLE
Qt PC Camera部分，Camera的x和y位置是正常情况的2倍

### ISSUE THREAD

**Issue by chenzilin** [yuq/v4l2-tester#1]
![111](https://cloud.githubusercontent.com/assets/6007305/26282614/49f4ff80-3e47-11e7-86a9-dc2abab49a84.png)

**Comment by chenzilin** [comment]
找到问题原因了，解决方法如下:
![11](https://cloud.githubusercontent.com/assets/6007305/26350129/b3925638-3fe4-11e7-95bb-b9dfae845e52.PNG)

**Comment by yuq** [comment]
子林兄提个pull request呗
